baseURL = 'https://sab0tage.com/'
languageCode = 'en-us'
title = 'sⒶb0t∀g∃'

theme = 'github.com/nodejh/hugo-theme-mini'


[params]
author = "cachicam0"
showToc = false
showPowerBy = false
copyright = " "
customCSS = [ "custom.css" ]
